# Generated by Django 3.0.8 on 2020-07-19 13:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
                ('phone_number', models.CharField(max_length=8, null=True)),
                ('price', models.FloatField(max_length=12, null=True)),
                ('url', models.ImageField(default='default.png', null=True, upload_to='')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 7, 19, 21, 21, 48, 227977))),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('cat', models.CharField(max_length=20)),
                ('logo', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=20)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.Cat')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adv.Cat')),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adv.Sub')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adv.Tag')),
            ],
            options={
                'unique_together': {('tag', 'sub', 'cat')},
            },
        ),
        migrations.AddField(
            model_name='sub',
            name='tag',
            field=models.ManyToManyField(through='adv.TagLink', to='adv.Tag'),
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(default='default.png', max_length=70, upload_to='')),
                ('ad', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='adv.Ad')),
            ],
        ),
        migrations.AddField(
            model_name='cat',
            name='tag',
            field=models.ManyToManyField(through='adv.TagLink', to='adv.Tag'),
        ),
        migrations.AddField(
            model_name='ad',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adv.Cat'),
        ),
        migrations.AddField(
            model_name='ad',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adv.Sub'),
        ),
        migrations.AddField(
            model_name='ad',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adv.Tag'),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
